### ISSUE TITLE
for some reason gml_Object_obj_mainchara_ch1_Draw_0 in deltarune 1.15 and gml_Object_obj_mainchara_Draw_0 in SURVEY_PROGRAM decompiles differently

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [UnderminersTeam/UndertaleModTool#1417]
### Describe the bug

in 1.15 there's <<'s that shouldn't be there

### Reproducing steps

decompile both of them

### Setup Details

version 0.5.1.0 (the decompiler isn't updated in 2 months...)

**Comment by Jacky720** [comment]
Not a bug. Enums in GMS2.3+ (the Chapter 2 version) compile incompletely, retaining the `<< 0` you're seeing. `<<` means "bitshift left", that is, turning 1 into 2 or 2 into 4... but because it's a 0, it makes no change to the actual value.

I guess it would be possible to make some kind of nonfunctional enum marker in the decompiler... but it wouldn't really affect anything.

**Comment by H-A-M-G-E-R** [comment]
also there's new instructions in the assembly in chapter 2 that aren't seen in survey_program

**Comment by Jacky720** [comment]
Yes, those instructions indicate the presence of enums.

**Comment by H-A-M-G-E-R** [comment]
see line 362 of UndertaleModLib/Decompiler/Decompiler.cs

**Comment by H-A-M-G-E-R** [comment]
one instruction is conv.b.v

**Comment by Jacky720** [comment]
That's because GameMaker added a boolean format, even though it basically still acts like an integer. The decompiler doesn't properly process that, pretty much ignores it in fact, but... there is no UTMT bug here. This is just stuff that changed in the game.

**Comment by H-A-M-G-E-R** [comment]
that's because i'm using the wrong compiler

**Comment by Jacky720** [comment]
Not a bug.
