### ISSUE TITLE
Can't modify data.win in Streaming For Love

### ISSUE THREAD

**Issue by SileNTViP** [UnderminersTeam/UndertaleModTool#1642]
### Describe the bug

When load data.win file
![Screenshot_3](https://github.com/krzys-h/UndertaleModTool/assets/25021045/fd311434-b8e3-480e-bc06-df0939545eff)
after saving the game does not start.

### Reproducing steps

1. Open data.win
2. Replace font sprite
3. Save new data.win

### Setup Details

1. UMT 0.5.1
2. Windows 11 Pro
3. GMS 2023.8

**Comment by Jacky720** [comment]
Do you have a link to the game in question? It seems very difficult to search and the closest I'm finding are Patreon pages (which, if the game has to be purchased through Patreon, would be good to clarify). Also, does the game still fail to save properly when using the latest bleeding edge rather than 0.5.1.0?

**Comment by SileNTViP** [comment]
mega.nz/file/cDUzDCDA#YLri4PsswFIzwYNoJKdRV_JguhEwxsfJk1L5mlcb23c
With the latest utility, the game still won't launch. Hanging in the task manager without errors.

**Comment by BenjaminUrquhart** [comment]
I want to say https://github.com/UnderminersTeam/UndertaleModTool/pull/1702 fixed this, as I can save and run the game fine with this commit, and the behavior you're reporting is identical to what this PR fixed.
