### ISSUE TITLE
Improve the "asset order swapping" function

### ISSUE THREAD

**Issue by UnknownSandwich** [UnderminersTeam/UndertaleModTool#1709]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

You can drag and place an asset "between two assets", and we can also use the mouse scroll to move the list while we are dragging an asset.

**Comment by BenjaminUrquhart** [comment]
The purpose of the asset order option is to fix mistakes caused by accidentally moving things around via scripts or forgetting to turn the option off. 

In most cases it's not something you should care about - if you're using it to arrange assets in a way that you can easily iterate over them in code I would suggest finding an alternative way to do that.

Basically, you shouldn't be using it enough for these features to be particularly helpful.
