### ISSUE TITLE
the new version of umt is unable to open my project but the old version works fine.

### ISSUE THREAD

**Issue by ErikTheGrate** [UnderminersTeam/UndertaleModTool#1739]
### Describe the bug

when trying to load my project in the latest version of UMT, it throws an error.

### Reproducing steps

https://www.mediafire.com/file/9t8m5ws4bfhvtb2/i_am_an_undertale.mkv/file

### Setup Details

1. UndertaleModTool version: the issue is with the latest bleeding edge version. the version that works is last modified 2/2/2023
2. Operating system:  Edition  = Windows 10 Home, Version = 22H2, Installed on = ‎12/‎20/‎2022, OS build = 19045.4291, Experience = Windows Feature Experience Pack 1000.19056.1000.0
3. GameMaker Game: the data.win file is a modified (using the working version of undertalemodtool) version of a game.droid file i extracted from a mobile port of the pizza tower snick demo. https://www.mediafire.com/file/62q70jg349t81a7/Infinite_Tower_of_pizza.win/file

**Comment by ErikTheGrate** [comment]
nope sorry. what i do know is that i can successfully run the file using the exe runner from the pizza tower snick demo. i believe my editing may have caused this because although i did not save the original file, i found what seems to be the same online and the version i found loads fine. https://thepizzano.itch.io/pizza-tower-mobile-sage-2019 sorry if i wasted your time. is there a way i could repair my file?

**Comment by Jacky720** [comment]
2.2.2.302, huh... there's always the option of identifying your changes, re-exporting those assets and code, and re-importing them to the original with a newer version...

Ah, that's interesting. The 2.3.2 detection is evidently because some sprites have an SVersion of 3, which was introduced in GMS 2.3.2 (and I think they're serializing with all the additional flags that implies too). The most likely way I see for that to happen-- might be wrong, in which case I dunno-- is CopySpriteBgFont.csx, which copies the SVersion from an external data file without checking for version compatibility. So you might also be able to re-save the existing modified version if you changed those flags back to 1 in UTMT 0.5.0.0.

**Comment by ErikTheGrate** [comment]
thanks. that worked!👍👍https://www.mediafire.com/file/3ijjun7k4yaf4ei/fixed_the_umt.mkv/file now i can enjoy the latest version of UMT. thanks for the help.
