### ISSUE TITLE
scr_namingscreen DELETING files when you save the game

### ISSUE THREAD

**Issue by PrHamidzadeh** [UnderminersTeam/UndertaleModTool#1812]
### Describe the bug

when i edit or even open scr_namingscreen about 9 lines delete itself and dont let me open undertale
when i open undertale without that 9 line, start menu can continue on first time and game freezes
the WEIRDEST thing i was ever seen

### Reproducing steps

1.edit scr_namingscreen
2.save or go to another file
3.somehow 9 lines go missing

### Setup Details

1. UNDERTALE MOD TOOL VERSION : 0.5.1.0
2. Windows 10 - 64-bit operating system, x64-based processor
3. Gamemaker Studios

**Comment by Miepee** [comment]
what game=?

**Comment by Jacky720** [comment]
This sounds like a well-known decompiler issue, #235. The tool contains a [fixed decompilation](https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModTool/Corrections/5903fc5cb042a728d4ad8ee9e949c6eb/Main/gml_Script_scr_namingscreen.gml) for Undertale's scr_namingscreen. If the workaround is sufficient*, we can close this issue as duplicate. Otherwise, it would be nice to know what nine lines you mean.

\* Note that the tool's default behavior is to decompile the code after compiling; this is why comments disappear and the code is reformatted. Because this runs the risk of breaking the script again if additional changes are made, it is advised to either use File > Settings > Profile mode (which disables this behavior) or to make changes to scr_namingscreen using an external editor.

**Comment by PrHamidzadeh** [comment]
> This sounds like a well-known decompiler issue, #235. The tool contains a [fixed decompilation](https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModTool/Corrections/5903fc5cb042a728d4ad8ee9e949c6eb/Main/gml_Script_scr_namingscreen.gml) for Undertale's scr_namingscreen. If the workaround is sufficient*, we can close this issue as duplicate. Otherwise, it would be nice to know what nine lines you mean.
> 
> * Note that the tool's default behavior is to decompile the code after compiling; this is why comments disappear and the code is reformatted. Because this runs the risk of breaking the script again if additional changes are made, it is advised to either use File > Settings > Profile mode (which disables this behavior) or to make changes to scr_namingscreen using an external editor.

Thank you
